name: release
on:
  workflow_dispatch:
jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: aosc/aosc-os:buildkit
      options: --platform=linux/amd64
    env:
      PACKAGENAME: jmcomic_linux_x64
    steps:
    - uses: actions/checkout@v7
    - name: Install deps
      run: |
        oma install pyside6 -y
        sed -i 's|exe = pyside_dir / '\''Qt'\'' / '\''libexec'\'' / qt_tool|exe = Path("/usr/lib/qt6/libexec") / qt_tool|' /usr/lib/python3.14/site-packages/PySide6/scripts/pyside_tool.py
    - name: Package tarball
      run: |
        python3 script/build_qrc.py
        tar --exclude='.git' -czf ${{ env.PACKAGENAME }}.tar.gz .
    - name: Upload
      uses: actions/upload-artifact@v7
      with:
        name: ${{ env.PACKAGENAME }}
        path: ${{ env.PACKAGENAME }}.tar.gz
        retention-days: 7
